server:
  port: 8100
spring:
  redis:
    host: 192.168.0.19
    port: 6379
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            exposedHeaders:
            - content-type
            allowedHeaders:
            - content-type
            allowCredentials: true
            allowedMethods:
            - GET
            - OPTIONS
            - PUT
            - DELETE
            - POST
      discovery:
        locator:
          #开启为所有服务都进行转发操作
          enabled: true
          #开启小写的服务ID
          lower-case-service-id: true
      routes:
        - id: cloud-eureka-client-user-service
          #lb代表是从注册中心获取
          uri: lb://cloud-eureka-client-user-service
          predicates:
            #通过Path方式对请求路径进行过滤
            - Path=/cloud-eureka-client-user-service/**
        - id: cloud-eureka-client-article-service
          uri: lb://cloud-eureka-client-article-service
          predicates:
            - Path=/cloud-eureka-client-article-service/**
          filters:
            #gateway网关的hystrix熔断器
            - name: Hystrix
              args:
                name: fallbackcmd
                #熔断时的回调地址
                fallbackUri: forward:/gateway/fallback
                #请求限流
            - name: RequestRateLimiter
              args:
                #允许用户每秒处理多少请求
                redis-rate-limiter.replenishRate: 10
                #令牌桶的数量，允许在1秒内完成的最大请求数
                redis-rate-limiter.burstCapacity: 15
                #按名称引用bean，@bean下面的方法名即是其在spring容器中的ID
                key-resolver: "#{@ipKeyResolver}"


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10000
    lease-expiration-duration-in-seconds: 10000
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://zqj:666666@localhost:8081/eureka/


